global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kubernetes'
    kubernetes_sd_configs:
      - role: node
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__meta_kubernetes_node_label_kubernetes_io_role]
        action: replace
        target_label: role
